### ISSUE TITLE
Emit async/sync data packets from the UART framing module.

### ISSUE THREAD

**Issue by squaresurf** [verypossible/harald#15]
#14 started the process of framing for async/sync data packets. All that remains is to figure out how to emit them to higher level users of harald.

**Comment by danielspofford** [comment]
Not sure when it changed, but this is happening. They will get tagged with `:error` because they come out as raw binaries we don't parse into pretty structs yet, but they get emitted to handlers and may be consumed.

**Comment by squaresurf** [comment]
Awesome! So to be clear, if I were to implement a handler in my app that depends on harald, then I could consume async/sync data with today's version of the code?

**Comment by fermuch** [comment]
I'm sorry to revive this closed thread, but:

> if I were to implement a handler in my app that depends on harald, then I could consume async/sync data with today's version of the code?

Is this possible? Is there an example of this?
